include:
  - project: 'blockchainlaboratory/gitlab-ci'
    ref: v0.0.4
    file: '/.gitlab-ci.yml'

stages:
  - build
  - test
  - autotest

build:
  stage: build
  script:
    - echo "Noop"
  only:
    - branches
  tags:
    - docker

test:
  stage: test
  before_script:
    - mkdir -p $(pwd)/${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
  script:
    - go test -v ./... -race -coverprofile=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}/coverage.out
  artifacts:
    paths:
      - ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}/*
  tags:
    - docker
  only:
    - branches
