include:
  - project: 'blockchainlaboratory/gitlab-ci'
    ref: v0.0.5
    file: '/.gitlab-ci.yml'

stages:
  - build
  - test
  - autotest

build:
  extends:
    - .noop
  stage: build
  only:
    - branches
  tags:
    - docker

test:
  extends:
    - .unit_tests
  stage: test
  tags:
    - docker
  only:
    - branches
