include:
  - project: 'blockchainlaboratory/gitlab-ci'
    ref: v0.0.4
    file: '/.gitlab-ci.yml'

stages:
  - build
  - test
  - autotest

build:
  stage: build
  script:
    - echo "Noop"
  only:
    - branches
  tags:
    - docker
