include:
  - project: 'blockchainlaboratory/gitlab-ci'
    ref: v0.0.6
    file: '/.gitlab-ci.yml'

stages:
  - test
  - autotest

test:
  extends:
    - .unit_tests
  stage: test
  only:
    - branches

autotest:
  extends:
    - .autotest
  stage: autotest
  rules:
    - if: $CI_COMMIT_BRANCH
      when: manual
  allow_failure: true
